name: Genji
services:
  - load: discord
    game: Chess
    jobs:
      - load: debug
      - load: verification
        channel: test
        grant: Member
        discourse:
          url: https://forum.rokkenjima.org
          topic_id: 73
          trust_level: 2
        lines:
          success: "Your identity has been verified."
          name_not_in_post: "You must mention your name as it appears here in your post."
          level_too_low: "It appears as though you have not yet reached Member status. Please participate on the forum for a few days and try again. Your current level is listed on your profile page."
          error: "An error is preventing me from verifying you. Please try again."
      - load: music
        channel: Staff
      - load: conversion
        lines:
          currency: "Last I checked, %s was about %s."
          currency_multi: "Last I checked, %s was about $%s, €%s, £%s or ¥%s."
  # - load: discourse
  #   url: https://forum.rokkenjima.org
